// Generated by CoffeeScript 1.8.0
(function() {
  var Math, Matrix, Random;

  Math = {};

  module.exports = Math;

  Matrix = require('./matrix').Matrix;

  Random = require('./random').Random;

  Math.Matrix = Matrix;

  Math.Random = Random;

}).call(this);
