# Dependencies
markdown:         redcarpet

# Permalinks
permalink:        pretty

# Server
destination:      docs/_site
plugins:          docs/_plugins
layouts:          docs/_layouts
collections:      null

encoding:         UTF-8

# sass
sass:
    sass_dir:     docs/_sass
    style:        :compressed

# Custom vars
current_version:  0.1.0
repo:             https://github.com/coffee-learn/coffee-learn

baseurl:          /coffee-learn

