# Dependencies
highlighter:      rouge
markdown:         redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      docs/_site
plugins:          docs/_plugins
layouts:          docs/_layouts
data_source:      docs/_data
collections:      null

host:             0.0.0.0
port:             4000
encoding:         UTF-8

# sass
sass:
    style:       :compressed

# Custom vars
current_version:  0.1.0
repo:             https://github.com/coffee-learn/coffee-learn

