// Generated by CoffeeScript 1.8.0
(function() {
  var LogisticRegression, MLP, NeuralNetwork, Sigmoid;

  LogisticRegression = require('./logistic_regression').LogisticRegression;

  Sigmoid = require('./base').Sigmoid;

  MLP = require('./mlp').MLP;

  NeuralNetwork = {};

  NeuralNetwork.LogisticRegression = LogisticRegression;

  NeuralNetwork.Sigmoid = Sigmoid;

  module.exports = NeuralNetwork;

}).call(this);
