// Generated by CoffeeScript 1.8.0
(function() {
  var Models, NeuralNetwork;

  Models = {};

  module.exports = Models;

  NeuralNetwork = require('./neuralnetwork/neuralnetwork');

  Models.NeuralNetwork = NeuralNetwork;

}).call(this);
