// Generated by CoffeeScript 1.8.0
(function() {
  var Datasets, Math, Models, Train, cflearn;

  cflearn = {};

  module.exports = cflearn;

  Math = require('./math/matrix');

  Models = require('./models/models');

  Train = require('./train/train');

  Datasets = require('./datasets/datasets');

  cflearn.Math = Math;

  cflearn.Models = Models;

  cflearn.Train = Train;

  cflearn.Datasets = Datasets;

}).call(this);
